apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  namespace: nginx-helm
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ default 1 .Values.replicas | int }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.application.image }}"
        ports:
        - containerPort: {{ .Values.application.containerPort | int }}     
        volumeMounts:
          - name: site
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html

      volumes:
        - name: site
          ConfigMap:
            name: {{ .Release.Name}}-cm