apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-helm-ingress
  namespace: nginx-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  rules:
    - host: nginx-helm.localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: nginx-helm-svc
                port:
                  number: 7800