{{if .Values.application.ingress.enabled}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-ingress
  namespace: nginx-helm
spec:
  ingressClassName: nginx

  rules:
    - host: {{.Release.Name}}.localhost
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{.Release.Name}}-svc
                port:
                  number: {{ .Values.application.userPort}}
{{end}}