{{- if .Values.application.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name}}
  namespace: nginx-helm
  labels:
    app: {{ .Release.Name}}
spec:
  rules:
    - host: {{ .Release.Name }}.localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-svc
              servicePort: {{ .Values.application.userPort }}
{{- end -}}