{{- if .Values.application.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
       nginx.ingress.kubernetes.io/rewrite-target: /
  labels:
    app.kubernetes.io/instance: nginx
  name: nginx-ingress
  namespace: nginx-helm

spec:
  ingressClassName: nginx
  rules:
    - host: s1.localhost
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-svc
                port:
                  number: {{ .Values.application.userPort}}
            path: /
            pathType: Prefix