apiVersion: v1
kind: Service
metadata:
  name: {{ .Release}}-svc
  namespace: {{ .Release}}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.application.userPort }}
      targetPort: {{ .Values.application.containerPort}}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release }}
