apiVersion: v1
kind: Service
metadata:
  name: {{ .Release}}-svc
  namespace: {{ .Release}}    
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.application.user-port }}
      targetPort: {{ .Values.application.container-port}}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release }}
